version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: energy-monitoring-db-prod
    environment:
      POSTGRES_DB: energy_monitoring
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - energy-monitoring-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Energy Monitoring API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy-monitoring-api-prod
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/energy_monitoring
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      NODE_ENV: production
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - energy-monitoring-network
    restart: unless-stopped
    command: sh -c "npm run db:setup && node dist/main"

volumes:
  postgres_data:

networks:
  energy-monitoring-network:
    driver: bridge 